# Code generated by moonworm : https://github.com/bugout-dev/moonworm
# Moonworm version : 0.2.4

import argparse
import json
import os
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

from brownie import Contract, network, project
from brownie.network.contract import ContractContainer
from eth_typing.evm import ChecksumAddress


PROJECT_DIRECTORY = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
BUILD_DIRECTORY = os.path.join(PROJECT_DIRECTORY, "build", "contracts")


def boolean_argument_type(raw_value: str) -> bool:
    TRUE_VALUES = ["1", "t", "y", "true", "yes"]
    FALSE_VALUES = ["0", "f", "n", "false", "no"]

    if raw_value.lower() in TRUE_VALUES:
        return True
    elif raw_value.lower() in FALSE_VALUES:
        return False

    raise ValueError(
        f"Invalid boolean argument: {raw_value}. Value must be one of: {','.join(TRUE_VALUES + FALSE_VALUES)}"
    )


def bytes_argument_type(raw_value: str) -> str:
    return raw_value


def get_abi_json(abi_name: str) -> List[Dict[str, Any]]:
    abi_full_path = os.path.join(BUILD_DIRECTORY, f"{abi_name}.json")
    if not os.path.isfile(abi_full_path):
        raise IOError(
            f"File does not exist: {abi_full_path}. Maybe you have to compile the smart contracts?"
        )

    with open(abi_full_path, "r") as ifp:
        build = json.load(ifp)

    abi_json = build.get("abi")
    if abi_json is None:
        raise ValueError(f"Could not find ABI definition in: {abi_full_path}")

    return abi_json


def contract_from_build(abi_name: str) -> ContractContainer:
    # This is workaround because brownie currently doesn't support loading the same project multiple
    # times. This causes problems when using multiple contracts from the same project in the same
    # python project.
    PROJECT = project.main.Project("moonworm", Path(PROJECT_DIRECTORY))

    abi_full_path = os.path.join(BUILD_DIRECTORY, f"{abi_name}.json")
    if not os.path.isfile(abi_full_path):
        raise IOError(
            f"File does not exist: {abi_full_path}. Maybe you have to compile the smart contracts?"
        )

    with open(abi_full_path, "r") as ifp:
        build = json.load(ifp)

    return ContractContainer(PROJECT, build)


class BasicAllianceFactory:
    def __init__(self, contract_address: Optional[ChecksumAddress]):
        self.contract_name = "BasicAllianceFactory"
        self.address = contract_address
        self.contract = None
        self.abi = get_abi_json("BasicAllianceFactory")
        if self.address is not None:
            self.contract: Optional[Contract] = Contract.from_abi(
                self.contract_name, self.address, self.abi
            )

    def deploy(
        self, alliance_registry: ChecksumAddress, base_uri: str, transaction_config
    ):
        contract_class = contract_from_build(self.contract_name)
        deployed_contract = contract_class.deploy(
            alliance_registry, base_uri, transaction_config
        )
        self.address = deployed_contract.address
        self.contract = deployed_contract
        return deployed_contract.tx

    def assert_contract_is_instantiated(self) -> None:
        if self.contract is None:
            raise Exception("contract has not been instantiated")

    def verify_contract(self):
        self.assert_contract_is_instantiated()
        contract_class = contract_from_build(self.contract_name)
        contract_class.publish_source(self.contract)

    def add_members(self, player_submissions: List, transaction_config) -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.addMembers(player_submissions, transaction_config)

    def admin(self, block_number: Optional[Union[str, int]] = "latest") -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.admin.call(block_identifier=block_number)

    def claim_invite(
        self,
        player: ChecksumAddress,
        nonce: int,
        signature: bytes,
        invite_nonce: int,
        invite_signature: bytes,
        transaction_config,
    ) -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.claimInvite(
            player, nonce, signature, invite_nonce, invite_signature, transaction_config
        )

    def frontend_uri(self, block_number: Optional[Union[str, int]] = "latest") -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.frontendURI.call(block_identifier=block_number)

    def get_address(
        self, salt: bytes, block_number: Optional[Union[str, int]] = "latest"
    ) -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.getAddress.call(salt, block_identifier=block_number)

    def init(self, base_uri: str, transaction_config) -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.init(base_uri, transaction_config)

    def instantiate(
        self,
        initial_admin: ChecksumAddress,
        player_submissions: List,
        salt: bytes,
        transaction_config,
    ) -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.instantiate(
            initial_admin, player_submissions, salt, transaction_config
        )

    def member_nonces(
        self, arg1: ChecksumAddress, block_number: Optional[Union[str, int]] = "latest"
    ) -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.memberNonces.call(arg1, block_identifier=block_number)

    def remove_member(self, player: ChecksumAddress, transaction_config) -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.removeMember(player, transaction_config)

    def set_admin_and_add_members(
        self, new_admin: ChecksumAddress, player_submissions: List, transaction_config
    ) -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.setAdminAndAddMembers(
            new_admin, player_submissions, transaction_config
        )


def get_transaction_config(args: argparse.Namespace) -> Dict[str, Any]:
    signer = network.accounts.load(args.sender, args.password)
    transaction_config: Dict[str, Any] = {"from": signer}
    if args.gas_price is not None:
        transaction_config["gas_price"] = args.gas_price
    if args.max_fee_per_gas is not None:
        transaction_config["max_fee"] = args.max_fee_per_gas
    if args.max_priority_fee_per_gas is not None:
        transaction_config["priority_fee"] = args.max_priority_fee_per_gas
    if args.confirmations is not None:
        transaction_config["required_confs"] = args.confirmations
    if args.nonce is not None:
        transaction_config["nonce"] = args.nonce
    return transaction_config


def add_default_arguments(parser: argparse.ArgumentParser, transact: bool) -> None:
    parser.add_argument(
        "--network", required=True, help="Name of brownie network to connect to"
    )
    parser.add_argument(
        "--address", required=False, help="Address of deployed contract to connect to"
    )
    if not transact:
        parser.add_argument(
            "--block-number",
            required=False,
            type=int,
            help="Call at the given block number, defaults to latest",
        )
        return
    parser.add_argument(
        "--sender", required=True, help="Path to keystore file for transaction sender"
    )
    parser.add_argument(
        "--password",
        required=False,
        help="Password to keystore file (if you do not provide it, you will be prompted for it)",
    )
    parser.add_argument(
        "--gas-price", default=None, help="Gas price at which to submit transaction"
    )
    parser.add_argument(
        "--max-fee-per-gas",
        default=None,
        help="Max fee per gas for EIP1559 transactions",
    )
    parser.add_argument(
        "--max-priority-fee-per-gas",
        default=None,
        help="Max priority fee per gas for EIP1559 transactions",
    )
    parser.add_argument(
        "--confirmations",
        type=int,
        default=None,
        help="Number of confirmations to await before considering a transaction completed",
    )
    parser.add_argument(
        "--nonce", type=int, default=None, help="Nonce for the transaction (optional)"
    )
    parser.add_argument(
        "--value", default=None, help="Value of the transaction in wei(optional)"
    )
    parser.add_argument("--verbose", action="store_true", help="Print verbose output")


def handle_deploy(args: argparse.Namespace) -> None:
    network.connect(args.network)
    transaction_config = get_transaction_config(args)
    contract = BasicAllianceFactory(None)
    result = contract.deploy(
        alliance_registry=args.alliance_registry,
        base_uri=args.base_uri,
        transaction_config=transaction_config,
    )
    print(result)
    if args.verbose:
        print(result.info())


def handle_verify_contract(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicAllianceFactory(args.address)
    result = contract.verify_contract()
    print(result)


def handle_add_members(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicAllianceFactory(args.address)
    transaction_config = get_transaction_config(args)
    result = contract.add_members(
        player_submissions=args.player_submissions,
        transaction_config=transaction_config,
    )
    print(result)
    if args.verbose:
        print(result.info())


def handle_admin(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicAllianceFactory(args.address)
    result = contract.admin(block_number=args.block_number)
    print(result)


def handle_claim_invite(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicAllianceFactory(args.address)
    transaction_config = get_transaction_config(args)
    result = contract.claim_invite(
        player=args.player,
        nonce=args.nonce_arg,
        signature=args.signature,
        invite_nonce=args.invite_nonce,
        invite_signature=args.invite_signature,
        transaction_config=transaction_config,
    )
    print(result)
    if args.verbose:
        print(result.info())


def handle_frontend_uri(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicAllianceFactory(args.address)
    result = contract.frontend_uri(block_number=args.block_number)
    print(result)


def handle_get_address(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicAllianceFactory(args.address)
    result = contract.get_address(salt=args.salt, block_number=args.block_number)
    print(result)


def handle_init(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicAllianceFactory(args.address)
    transaction_config = get_transaction_config(args)
    result = contract.init(
        base_uri=args.base_uri, transaction_config=transaction_config
    )
    print(result)
    if args.verbose:
        print(result.info())


def handle_instantiate(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicAllianceFactory(args.address)
    transaction_config = get_transaction_config(args)
    result = contract.instantiate(
        initial_admin=args.initial_admin,
        player_submissions=args.player_submissions,
        salt=args.salt,
        transaction_config=transaction_config,
    )
    print(result)
    if args.verbose:
        print(result.info())


def handle_member_nonces(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicAllianceFactory(args.address)
    result = contract.member_nonces(arg1=args.arg1, block_number=args.block_number)
    print(result)


def handle_remove_member(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicAllianceFactory(args.address)
    transaction_config = get_transaction_config(args)
    result = contract.remove_member(
        player=args.player, transaction_config=transaction_config
    )
    print(result)
    if args.verbose:
        print(result.info())


def handle_set_admin_and_add_members(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicAllianceFactory(args.address)
    transaction_config = get_transaction_config(args)
    result = contract.set_admin_and_add_members(
        new_admin=args.new_admin,
        player_submissions=args.player_submissions,
        transaction_config=transaction_config,
    )
    print(result)
    if args.verbose:
        print(result.info())


def generate_cli() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="CLI for BasicAllianceFactory")
    parser.set_defaults(func=lambda _: parser.print_help())
    subcommands = parser.add_subparsers()

    deploy_parser = subcommands.add_parser("deploy")
    add_default_arguments(deploy_parser, True)
    deploy_parser.add_argument(
        "--alliance-registry", required=True, help="Type: address"
    )
    deploy_parser.add_argument(
        "--base-uri", required=True, help="Type: string", type=str
    )
    deploy_parser.set_defaults(func=handle_deploy)

    verify_contract_parser = subcommands.add_parser("verify-contract")
    add_default_arguments(verify_contract_parser, False)
    verify_contract_parser.set_defaults(func=handle_verify_contract)

    add_members_parser = subcommands.add_parser("add-members")
    add_default_arguments(add_members_parser, True)
    add_members_parser.add_argument(
        "--player-submissions", required=True, help="Type: tuple[]", nargs="+"
    )
    add_members_parser.set_defaults(func=handle_add_members)

    admin_parser = subcommands.add_parser("admin")
    add_default_arguments(admin_parser, False)
    admin_parser.set_defaults(func=handle_admin)

    claim_invite_parser = subcommands.add_parser("claim-invite")
    add_default_arguments(claim_invite_parser, True)
    claim_invite_parser.add_argument("--player", required=True, help="Type: address")
    claim_invite_parser.add_argument(
        "--nonce-arg", required=True, help="Type: uint32", type=int
    )
    claim_invite_parser.add_argument(
        "--signature", required=True, help="Type: bytes", type=bytes_argument_type
    )
    claim_invite_parser.add_argument(
        "--invite-nonce", required=True, help="Type: uint32", type=int
    )
    claim_invite_parser.add_argument(
        "--invite-signature",
        required=True,
        help="Type: bytes",
        type=bytes_argument_type,
    )
    claim_invite_parser.set_defaults(func=handle_claim_invite)

    frontend_uri_parser = subcommands.add_parser("frontend-uri")
    add_default_arguments(frontend_uri_parser, False)
    frontend_uri_parser.set_defaults(func=handle_frontend_uri)

    get_address_parser = subcommands.add_parser("get-address")
    add_default_arguments(get_address_parser, False)
    get_address_parser.add_argument(
        "--salt", required=True, help="Type: bytes32", type=bytes_argument_type
    )
    get_address_parser.set_defaults(func=handle_get_address)

    init_parser = subcommands.add_parser("init")
    add_default_arguments(init_parser, True)
    init_parser.add_argument("--base-uri", required=True, help="Type: string", type=str)
    init_parser.set_defaults(func=handle_init)

    instantiate_parser = subcommands.add_parser("instantiate")
    add_default_arguments(instantiate_parser, True)
    instantiate_parser.add_argument(
        "--initial-admin", required=True, help="Type: address"
    )
    instantiate_parser.add_argument(
        "--player-submissions", required=True, help="Type: tuple[]", nargs="+"
    )
    instantiate_parser.add_argument(
        "--salt", required=True, help="Type: bytes32", type=bytes_argument_type
    )
    instantiate_parser.set_defaults(func=handle_instantiate)

    member_nonces_parser = subcommands.add_parser("member-nonces")
    add_default_arguments(member_nonces_parser, False)
    member_nonces_parser.add_argument("--arg1", required=True, help="Type: address")
    member_nonces_parser.set_defaults(func=handle_member_nonces)

    remove_member_parser = subcommands.add_parser("remove-member")
    add_default_arguments(remove_member_parser, True)
    remove_member_parser.add_argument("--player", required=True, help="Type: address")
    remove_member_parser.set_defaults(func=handle_remove_member)

    set_admin_and_add_members_parser = subcommands.add_parser(
        "set-admin-and-add-members"
    )
    add_default_arguments(set_admin_and_add_members_parser, True)
    set_admin_and_add_members_parser.add_argument(
        "--new-admin", required=True, help="Type: address"
    )
    set_admin_and_add_members_parser.add_argument(
        "--player-submissions", required=True, help="Type: tuple[]", nargs="+"
    )
    set_admin_and_add_members_parser.set_defaults(func=handle_set_admin_and_add_members)

    return parser


def main() -> None:
    parser = generate_cli()
    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
